/* tslint:disable */
/* eslint-disable */
/**
 * Fitness-app
 * ### REST  Routes is following REST standard (Richardson level 3)  <details><summary>Detailed specification</summary> <p>  **List:**   - `GET /<resources>/`     - Get the list of **<resources>** as admin   - `GET /user/<user_id>/<resources>/`     - Get the list of **<resources>** for a given **<user_id>**     - Output a **403** if logged user is not **<user_id>**  **Detail:**   - `GET /<resources>/<resource_id>`     - Get the detail for **<resources>** of id **<resource_id>**     - Output a **404** if not found   - `GET /user/<user_id>/<resources>/<resource_id>`     - Get the list of **<resources>** for a given **user_id**     - Output a **404** if not found     - Output a **403** if:       - Logged user is not **<user_id>**       - The **<user_id>** have no access to **<resource_id>**  **Creation / Edition / Replacement / Suppression:**   - `<METHOD>` is:     - **POST** for creation     - **PATCH** for update (one or more fields)     - **PUT** for replacement (all fields, not used)     - **DELETE** for suppression (all fields, not used)   - `<METHOD> /<resources>/<resource_id>`     - Create **<resources>** with id **<resource_id>** as admin     - Output a **400** if **<resource_id>** conflicts with existing **<resources>**   - `<METHOD> /user/<user_id>/<resources>/<resource_id>`     - Create **<resources>** with id **<resource_id>** as a given **user_id**     - Output a **409** if **<resource_id>** conflicts with existing **<resources>**     - Output a **403** if:       - Logged user is not **<user_id>**       - The **<user_id>** have no access to **<resource_id>** </p> </details>
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

export const BASE_PATH = "http://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface RequestArgs
 */
export interface RequestArgs {
    url: string;
    options: RawAxiosRequestConfig;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath ?? basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    constructor(public field: string, msg?: string) {
        super(msg);
        this.name = "RequiredError"
    }
}

interface ServerMap {
    [key: string]: {
        url: string,
        description: string,
    }[];
}

/**
 *
 * @export
 */
export const operationServerMap: ServerMap = {
}
